#!/usr/bin/env python3

# Copyright (C) 2021-2025  tuxifreund <kaiser.barbarossa@yandex.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


import configparser
from pathlib import Path
import argparse
import os
import tempfile
import gi
gi.require_version('WebKit', '6.0')
gi.require_version('Gtk', '4.0')
gi.require_version('Gdk', '4.0')
from gi.repository import Gtk, Gdk, GLib, WebKit

argparser = argparse.ArgumentParser(description='A simple and lightweight browser written in Python.')
argparser.add_argument('url', help='URL/command to open/execute at startup', nargs='*')
argparser.add_argument('--basedir', '-B', help='Base directory')
argparser.add_argument('--temp-dir', '-t', help='Use a temporary base directory', action='store_true')
args = argparser.parse_args()

# Create needed directories

if not args.temp_dir:
    try:
        basedir = os.environ['MYBROWSE_HOME']
    except KeyError:
        try:
            if len(args.basedir) > 0:
                basedir = args.basedir[0:]
            else:
                basedir = Path.home()
        except TypeError:
            basedir = Path.home()
else:
    basedir = tempfile.mkdtemp(prefix='mybrowse-')

dir_tuple = [(f"{basedir}/.config/mybrowse", "configuration directory"),
(f"{basedir}/.local/share/mybrowse/themes", "theme directory"),
(f"{basedir}/.local/share/mybrowse/extensions", "extension directory")]

for (directory, description) in dir_tuple:
    if not Path(directory).is_dir():
        try:
            Path(directory).mkdir(parents=True)
            print(f'Create {description}')
        except OSError as e:
            print(e)
            pass

conf_file = f"{basedir}/.config/mybrowse/mybrowse.cfg"

config = configparser.ConfigParser()

if not Path(conf_file).exists():
        print('No configuration found')
        config['General'] = {'home': 'https://lite.duckduckgo.com',
                             'search': 'https://duckduckgo.com/?q='}
        config['Browser'] = {}
        with open(conf_file, 'w') as configfile:
                config.write(configfile)

config.read(['/etc/mybrowse/mybrowse.cfg', conf_file])
searchengine = config['General']['search']
startpage = config['General']['home']

extension_dir = f"{basedir}/.local/share/mybrowse/extensions/"
theme_dir = f"{basedir}/.local/share/mybrowse/themes/"
conf_dir = f"{basedir}/.config/mybrowse/"

def editconfig(settings):
    key = settings.split('=', 1)[0]
    value = settings.split('=', 1)[1]
    config[key.split('.')[0]][key.split('.')[1]] = value
    with open(conf_file, 'w') as configfile:
        config.write(configfile)

def links(url):
    if not url.startswith(':'):
        if not ":" in url:
            if url.startswith('/'):
               href = f'file://{url}'
            elif url.startswith('~'):
               href = f"file://{str(Path(url).expanduser())}"
            else:
               href = f'https://{url}'
        elif url == "about:bookmarks":
            href = f'file://{conf_dir}bookmarks.html'
        elif url == "about:history":
            href = f'file://{conf_dir}history'
        elif url == 'about:home':
            href = startpage
        elif '://' in url: # Custom "protocols"
            try:
                for key in config['Protocols']:
                    try:
                        href = f"{config['Protocols'][url.split('://', 1)[0]]}{url.split('://', 1)[1]}"
                    except KeyError:
                        href = url
            except KeyError:
                href = url
        else:
            href = url
    else:
        if url.startswith(':exec'):
            os.system(url.split(':exec ', 1)[1])
        elif url == ':report':
           href = 'https://github.com/KaiserBarbarossa/MyBrowse/issues/new'
        elif url == ':home':
           href = startpage
        elif url.startswith(':open') or url.startswith(':o') or url.startswith(':e'):
           href = links(url.split(' ', 1)[1])
        elif url.startswith(':q'):
            app.quit()
        elif url.startswith(':set'):
            editconfig(url.split(':set ', 1)[1])
        else:
            href = url
    try:
        try:
            host = GLib.Uri.get_host(GLib.uri_parse(href, GLib.UriFlags.ENCODED))
            for key in config['Redirects']:
                try:
                    split = GLib.uri_split(href, GLib.UriFlags.ENCODED)
                    href = GLib.uri_join(GLib.UriFlags.ENCODED, split[0],
                        split[1], config['Redirects'][host], split[3], split[4],
                        split[5], split[6])
                except KeyError:
                    pass
        except KeyError:
            pass
        # Use Punycode
        try:
            if config['Browser']['ascii-urls'] == 'False':
                pass
            else:
                split = GLib.uri_split(href, GLib.UriFlags.ENCODED)
                href = GLib.uri_join(GLib.UriFlags.ENCODED, split[0], split[1],
                        GLib.hostname_to_ascii(split[2]), split[3], split[4],
                        split[5], split[6])
        except KeyError:
            config['Browser']['ascii-urls'] = 'True'
            with open(conf_file, 'w') as configfile:
                config.write(configfile)
        return href
    except UnboundLocalError:
        pass

if len(args.url) > 0:
        starturl = ' '.join(args.url[0:])
else:
        starturl = startpage

class Browser(Gtk.ApplicationWindow):
    def __init__(self, **kargs):
        super().__init__(**kargs, title='MyBrowse')

        styleprovider = Gtk.CssProvider()
        try:
            cssfile = f"{theme_dir}{config['General']['theme']}/style.css"
            styleprovider.load_from_path(cssfile)
        except KeyError:
            pass
        if Path(f'{conf_dir}style.css').exists():
            styleprovider.load_from_path(f"{conf_dir}style.css")
        screen = Gdk.Display.get_default()
        Gtk.StyleContext.add_provider_for_display(screen, styleprovider,
                                    Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)

        self.context = WebKit.WebContext.get_default()
        self.context.set_web_process_extensions_directory(extension_dir)

        self.view = WebKit.WebView.new()

        self.vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.vbox.set_spacing(10)
        self.set_icon_name('browser')

        self.menu = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL)
        self.menu.expand = False
        self.back = Gtk.Button.new_from_icon_name('go-previous')
        self.back.set_tooltip_text('One page back (Ctrl + Z)')
        self.menu.append(self.back)
        self.forward = Gtk.Button.new_from_icon_name('go-next')
        self.forward.set_tooltip_text('One page forward (Ctrl + Y)')
        self.menu.append(self.forward)
        self.reload = Gtk.Button.new_from_icon_name('view-refresh')
        self.reload.set_tooltip_text('Reload current page (Ctrl + R)')
        self.menu.append(self.reload)
        self.home = Gtk.Button.new_from_icon_name('go-home')
        self.home.set_tooltip_text('Open home page')
        self.menu.append(self.home)
        self.bookmarker = Gtk.Button.new_from_icon_name('bookmark-new')
        self.bookmarker.set_tooltip_text('Bookmark current page (Ctrl + B)')
        self.menu.append(self.bookmarker)
        self.searchbar = Gtk.SearchEntry()
        self.searchbar.set_name('searchbar')
        self.menu.append(self.searchbar)
        
        self.back.connect("clicked", self.go_back)
        self.forward.connect("clicked", self.go_forward)
        self.reload.connect("clicked", self.go_reload)
        self.home.connect("clicked", self.go_home)
        self.searchbar.connect("activate", self.search)
        self.bookmarker.connect("clicked", self.set_bookmark)
        self.vbox.append(self.menu)

        self.addressbar = Gtk.Entry()
        self.addressbar.set_text(starturl)
        self.addressbar.set_name('addressbar')
        self.vbox.append(self.addressbar)
        
        self.addressbar.connect("activate", self.change_url)

        self.findcontroller = WebKit.FindController(web_view=self.view)

        self.sw = Gtk.ScrolledWindow()
        self.sw.set_child(self.view)
        self.sw.set_vexpand(True)

        self.vbox.append(self.sw)
        self.set_child(self.vbox)
        self.view.load_uri(links(starturl))
        self.view.connect("notify::uri", self.change_uri)
        self.view.connect("notify::title", self.change_title)
        self.view.connect("mouse-target-changed", self.link_hover)
        self.view.connect("notify::estimated-load-progress", self.progressbar)
        keycont = Gtk.EventControllerKey()
        keycont.connect("key-pressed", self.keybinding)
        self.add_controller(keycont)
        scrollcont = Gtk.EventControllerScroll()
        scrollcont.connect("scroll-begin", self.mousebindings)

    def str_to_bool(self, string):
        """
        Convert a string to its boolean. Every other string than "True" and "False"
        is ignored and a ValueError is raised.
        """
        if str(string).lower() == 'true':
            return True
        elif str(string).lower() == 'false':
            return False
        raise ValueError(f'Cannot convert string to bool: {str(string)}')

    def configuration(self, *args):
        settings = self.view.get_settings()
        try:
            settings.set_property('enable-javascript',
                    self.str_to_bool(config['Browser']['js']))
        except KeyError:
            print('JavaScript not explicit disabled.\r')
            config['Browser']['js'] = 'True'
            with open(conf_file, 'w') as configfile:
                config.write(configfile)
        try:
            settings.set_property('enable_write_console_messages_to_stdout',
                    self.str_to_bool(config['General']['debug']))
        except KeyError:
            pass
        try:
             settings.set_property('user-agent', config['Browser']['user-agent'])
        except KeyError:
             print('User-Agent value not set. Use fallback value\r')
        try:
             settings.set_property('enable-developer-extras',
                     self.str_to_bool(config['Browser']['firebug']))
        except KeyError:
             settings.set_property('enable-developer-extras', 'True')
             print('Firebug value not set. Use fallback value\r')
             config['Browser']['firebug'] = 'True'
             with open(conf_file, 'w') as configfile:
                     config.write(configfile)
        try:
            settings.set_property('enable-webgl', self.str_to_bool(config['Browser']['webgl']))
        except KeyError:
            settings.set_property('enable-webgl', 'True')
            print('WebGL setting not set. Use fallback value\r')
            config['Browser']['webgl'] = 'True'
            with open(conf_file, 'w') as configfile:
                    config.write(configfile)
        try:
            self.view.set_zoom_level(float(config['General']['zoom']))
        except KeyError:
            pass
        try:
            settings.set_property('zoom-text-only',
                    config['Browser']['zoom-text-only'])
        except KeyError:
            pass
        try:
            self.context.set_preferred_languages(config['General']['language'])
        except KeyError:
            pass

        # Cookie accept settings
        self.network_session = WebKit.NetworkSession.new_ephemeral()
        self.cookie_manager = self.network_session.get_cookie_manager()
        try:
            if config['Browser']['cookies'] == 'ALWAYS':
                self.cookie_manager.set_accept_policy(WebKit.CookieAcceptPolicy.ALWAYS)
            elif config['Browser']['cookies'] == 'NO_THIRD_PARTY':
                self.cookie_manager.set_accept_policy(WebKit.CookieAcceptPolicy.NO_THIRD_PARTY)
            elif config['Browser']['cookies'] == 'NEVER':
                self.cookie_manager.set_accept_policy(WebKit.CookieAcceptPolicy.NEVER)
        except KeyError:
            self.cookie_manager.set_accept_policy(WebKit.CookieAcceptPolicy.NO_THIRD_PARTY)
            config['Browser']['cookies'] = 'NO_THIRD_PARTY'
            with open(conf_file, 'w') as configfile:
                    config.write(configfile)

        # Persistent Cookie storage
        try:
            if config['Browser']['persistent-cookies'] == 'True':
                storage = WebKit.CookiePersistentStorage.TEXT
                try:
                    self.cookie_manager.set_persistent_storage(str(Path(
                        config['Browser']['cookiepath']).expanduser()), storage)
                except KeyError:
                    self.cookie_manager.set_persistent_storage('/tmp/mybrowse-cookies.txt', storage)
                    config['Browser']['cookiepath'] = '/tmp/mybrowse-cookies.txt'
                    with open(conf_file, 'w') as configfile:
                        config.write(configfile)
        except KeyError:
            pass


    def change_url(self, widget):
        url = self.addressbar.get_text()
        if url in (':back', ':undo', ':u'):
            self.view.go_back()
        elif url in (':forward', ':redo', ':r'):
            self.view.go_forward()
        elif url in (':reload', ':rl'):
            self.view.reload()
        elif url.startswith(':/'):
            self.search_page(url.split(':/', 1)[1])
        else:
            try:
                self.view.load_uri(links(url))
            except TypeError:
                pass

    def change_title(self, widget, data, *arg):
        title = widget.get_title()
        if title == '':
                self.set_title('MyBrowse')
        else:
                self.set_title(f'{title} - MyBrowse')

    def change_uri(self, widget, data, *arg):
        uri = widget.get_uri()
        try:
            self.view.load_uri(links(uri))
            self.addressbar.set_text(uri)
        except TypeError:
            pass
        history = open(f'{conf_dir}history', 'a')
        history.write(f'{uri}\r\n')
        history.close()

    def go_back(self, widget):
        self.view.go_back()

    def go_forward(self, widget):
        self.view.go_forward()

    def go_reload(self, widget):
        self.view.reload()

    def go_home(self, widget):
        self.addressbar.set_text(startpage)
        self.view.load_uri(startpage)

    def search(self, searchbar):
        searchstring = self.searchbar.get_text()
        self.view.load_uri(f'{links(searchengine)}'
                           f'{GLib.uri_escape_string(searchstring,"", True)}')

    def set_bookmark(self, widget):
        url = self.addressbar.get_text()
        title = self.view.get_title()
        bm_file_path = f'{conf_dir}bookmarks.html'
        bm_file =  open(bm_file_path, 'a+')
        if open(bm_file_path, 'r').read() == "":
            bm_content = f'<!DOCTYPE html>\n<head>\n<meta charset="utf-8">\n</head>\n<body>\n<a href="{url}">{title}</a><br>\r\n'
        else:
            bm_content = f'<a href="{url}">{title}</a><br>\r\n'
        bm_file.write(bm_content)
        bm_file.close()

    def link_hover(self, widget, hit_test, *args):
        if not (self.addressbar.has_focus() and self.addressbar.get_text().startswith(':')):
            if hit_test.get_link_uri() is not None:
                self.addressbar.set_text(hit_test.get_link_uri())
            else:
                self.addressbar.set_text(widget.get_uri())

    def progressbar(self, widget, data, *arg):
        amount = widget.get_estimated_load_progress()
        if not amount == 1:
            self.addressbar.set_progress_fraction(amount)
        else:
            self.addressbar.set_progress_fraction(0)
            self.view.grab_focus()

    def search_page(self, *args):
        keyword = args[0]
        if not keyword == "":
            self.findcontroller.search(keyword, WebKit.FindOptions.CASE_INSENSITIVE,
                    WebKit.FindOptions.WRAP_AROUND)

    def mousebindings(self, widget, event):
        if event.get_state() & Gdk.ModifierType.CONTROL_MASK:
            scrolldir = event.get_scroll_deltas()[2]
            if scrolldir > 0:
                self.view.set_zoom_level(self.view.get_zoom_level() - 0.1)
            elif scrolldir < 0:
                self.view.set_zoom_level(self.view.get_zoom_level() + 0.1)

    def keybinding(self, eventcontroller, keyval, keycode, state):
        if (keyval == Gdk.keyval_from_name('d') and
            state & Gdk.ModifierType.CONTROL_MASK):
                self.set_bookmark(self.view)
        if (keyval == Gdk.keyval_from_name('r') and
            state & Gdk.ModifierType.CONTROL_MASK):
                self.view.reload()
        if keyval == Gdk.KEY_F5:
                self.view.reload()
        if (keyval == Gdk.KEY_F5 and
            state & Gdk.ModifierType.SHIFT_MASK):
                self.view.reload_bypass_cache()
        if (keyval == Gdk.keyval_from_name('z') and
            state & Gdk.ModifierType.CONTROL_MASK):
                self.view.go_back()
        if (keyval == Gdk.keyval_from_name('y') and
            state & Gdk.ModifierType.CONTROL_MASK):
                self.view.go_forward()
        if (keyval == Gdk.keyval_from_name('0') and
            state & Gdk.ModifierType.CONTROL_MASK):
                self.view.set_zoom_level(1)
        if (keyval == Gdk.unicode_to_keyval(ord('+')) and
            state & Gdk.ModifierType.CONTROL_MASK):
                self.view.set_zoom_level(self.view.get_zoom_level() + 0.1)
        if (keyval == Gdk.unicode_to_keyval(ord('-')) and
            state & Gdk.ModifierType.CONTROL_MASK):
                self.view.set_zoom_level(self.view.get_zoom_level() - 0.1)
        if (keyval == Gdk.keyval_from_name('q') and
            state & Gdk.ModifierType.CONTROL_MASK):
                self.close()
        if (keyval == Gdk.keyval_from_name('l') and
            state & Gdk.ModifierType.CONTROL_MASK):
               self.addressbar.grab_focus()
        if (keyval == Gdk.KEY_Escape and
            self.addressbar.get_text().startswith(':/')):
                self.findcontroller.search_finish()
        if (keyval == Gdk.KEY_Escape and
            (self.addressbar.get_text() is not self.view.get_uri()
            or self.addressbar.get_text().startswith(':/'))):
            self.addressbar.set_text(self.view.get_uri())
        if (keyval == Gdk.KEY_Escape and
            self.addressbar.get_text() == self.view.get_uri()):
               self.addressbar.grab_focus()
        if (keyval == Gdk.keyval_from_name('f') and
            state & Gdk.ModifierType.CONTROL_MASK):
            self.addressbar.grab_focus()
            self.addressbar.set_text(':/')
            self.addressbar.set_position(-1)
        if (keyval == Gdk.keyval_from_name('k') and
            state & Gdk.ModifierType.CONTROL_MASK):
            self.searchbar.grab_focus()

def on_activate(app):
    win = Browser(application=app)
    win.configuration()
    try:
        win.set_default_size(float(config['Browser']['width']),
                             float(config['Browser']['height']))
    except KeyError:
        win.maximize()
    win.present()

if __name__ == "__main__":
    app = Gtk.Application()
    app.connect('activate', on_activate)
    app.run(None)
